### PR TITLE
Fix reading executable names of 64-bit apps from 32-bit python

### PR DESCRIPTION
**Pull request by daanzu**

### CODE REVIEW

**Comment by synkarius** [comment]
I would very much like to see this go through. I can confirm that it works.

**Comment by synkarius** [comment]
However, it seems to break FocusWindow._execute(), and I can't figure out why.

**Comment by daanzu** [comment]
How does it break break FocusWindow? It seems to work for me.

**Comment by synkarius** [comment]
Sorry, I had written my BringApp command wrong, nothing wrong with this patch.

**Comment by RadixSeven** [comment]
The delay in merging this pull-request is causing forking. See https://github.com/synkarius/caster/wiki/64-bit-window-executables

**Comment by chilimangoes** [comment]
Looks like this issue has been fixed in the master branch via [this commit](https://github.com/t4ngo/dragonfly/commit/b3c5d045391b97e928bbce6da23adf141ac6c5a7), so this pull request can probably be closed.

**Pull request closed without merging**
